# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: magazzino.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmagazzino.proto\x12\tmagazzino\"$\n\x08\x61rticolo\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\"\x16\n\x07msg_ack\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\"\x1b\n\x0bmsg_preleva\x12\x0c\n\x04tipo\x18\x01 \x01(\t2\x84\x01\n\x11gestioneMagazzino\x12\x35\n\x08\x64\x65posita\x12\x13.magazzino.articolo\x1a\x12.magazzino.msg_ack\"\x00\x12\x38\n\x07preleva\x12\x16.magazzino.msg_preleva\x1a\x13.magazzino.articolo\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'magazzino_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARTICOLO']._serialized_start=30
  _globals['_ARTICOLO']._serialized_end=66
  _globals['_MSG_ACK']._serialized_start=68
  _globals['_MSG_ACK']._serialized_end=90
  _globals['_MSG_PRELEVA']._serialized_start=92
  _globals['_MSG_PRELEVA']._serialized_end=119
  _globals['_GESTIONEMAGAZZINO']._serialized_start=122
  _globals['_GESTIONEMAGAZZINO']._serialized_end=254
# @@protoc_insertion_point(module_scope)
