# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import productM_pb2 as productM__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in productM_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ProductManagerStub(object):
    """Generated according to https://cloud.google.com/apis/design/standard_methods
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sell = channel.unary_unary(
                '/productM.ProductManager/Sell',
                request_serializer=productM__pb2.msg_sell.SerializeToString,
                response_deserializer=productM__pb2.msg_ack.FromString,
                _registered_method=True)
        self.Buy = channel.unary_unary(
                '/productM.ProductManager/Buy',
                request_serializer=productM__pb2.msg_buy.SerializeToString,
                response_deserializer=productM__pb2.msg_sell.FromString,
                _registered_method=True)


class ProductManagerServicer(object):
    """Generated according to https://cloud.google.com/apis/design/standard_methods
    """

    def Sell(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Buy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sell': grpc.unary_unary_rpc_method_handler(
                    servicer.Sell,
                    request_deserializer=productM__pb2.msg_sell.FromString,
                    response_serializer=productM__pb2.msg_ack.SerializeToString,
            ),
            'Buy': grpc.unary_unary_rpc_method_handler(
                    servicer.Buy,
                    request_deserializer=productM__pb2.msg_buy.FromString,
                    response_serializer=productM__pb2.msg_sell.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'productM.ProductManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('productM.ProductManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductManager(object):
    """Generated according to https://cloud.google.com/apis/design/standard_methods
    """

    @staticmethod
    def Sell(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productM.ProductManager/Sell',
            productM__pb2.msg_sell.SerializeToString,
            productM__pb2.msg_ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Buy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productM.ProductManager/Buy',
            productM__pb2.msg_buy.SerializeToString,
            productM__pb2.msg_sell.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
