# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: productM.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproductM.proto\x12\x08productM\"!\n\x08msg_sell\x12\x15\n\rserial_number\x18\x01 \x01(\x05\"\t\n\x07msg_buy\"\x16\n\x07msg_ack\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t2q\n\x0eProductManager\x12/\n\x04Sell\x12\x12.productM.msg_sell\x1a\x11.productM.msg_ack\"\x00\x12.\n\x03\x42uy\x12\x11.productM.msg_buy\x1a\x12.productM.msg_sell\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'productM_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSG_SELL']._serialized_start=28
  _globals['_MSG_SELL']._serialized_end=61
  _globals['_MSG_BUY']._serialized_start=63
  _globals['_MSG_BUY']._serialized_end=72
  _globals['_MSG_ACK']._serialized_start=74
  _globals['_MSG_ACK']._serialized_end=96
  _globals['_PRODUCTMANAGER']._serialized_start=98
  _globals['_PRODUCTMANAGER']._serialized_end=211
# @@protoc_insertion_point(module_scope)
