# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\x12\x06\x63lient\"\x1a\n\x0cmsg_deposita\x12\n\n\x02id\x18\x01 \x01(\t\"\r\n\x0bmsg_preleva\" \n\x0cmsg_response\x12\x10\n\x08response\x18\x01 \x01(\t2{\n\x07\x63ommand\x12\x38\n\x08\x64\x65posita\x12\x14.client.msg_deposita\x1a\x14.client.msg_response\"\x00\x12\x36\n\x07preleva\x12\x13.client.msg_preleva\x1a\x14.client.msg_response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSG_DEPOSITA']._serialized_start=24
  _globals['_MSG_DEPOSITA']._serialized_end=50
  _globals['_MSG_PRELEVA']._serialized_start=52
  _globals['_MSG_PRELEVA']._serialized_end=65
  _globals['_MSG_RESPONSE']._serialized_start=67
  _globals['_MSG_RESPONSE']._serialized_end=99
  _globals['_COMMAND']._serialized_start=101
  _globals['_COMMAND']._serialized_end=224
# @@protoc_insertion_point(module_scope)
